baseURL = "https://imjoshholloway.uk/"
languageCode = "en-gb"
title = "The Ramblings of Josh"
theme = "cactus"
googleAnalytics = "UA-167963804-1"

[menu]
  [[menu.main]]
    name = "Resume"
    identifier = "resume"
    url = "/resume.pdf"
    weight = -110

[params]
	name = "Josh Holloway"
	description = "Ramblings of a madman"
	bio = "Father | Husband | Software Engineer"
	twitter = "imjoshholloway"

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/imjoshholloway"
    github   = "https://www.github.com/imjoshholloway"
    linkedin = "https://uk.linkedin.com/in/imjoshholloway"